Feature/sip 1043 documentation update
IKOR-GmbH/sip-framework pull request #103
Opened 2022-04-05 14:28 UTC by Dzuci

# Description

Changed archetype command to be in one line and added copy button.

## Type of change

Please delete options that are not relevant.
- [ ] This change requires a documentation update

# How Has This Been Tested?
Document reviewed.
Copy function tested.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing (regression) unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-07 07:22 UTC, Nemikor submitted a review, later dismissed

2022-04-19 13:06 UTC, LetoBukarica requested changes

2022-04-19 13:06 UTC, LetoBukarica commented on mkdocs.yml
> +    - javascript/copy_maven_command.js
@Nemikor Can you just change this file to be something like copy_to_clipboard.js?

2022-04-19 13:06 UTC, LetoBukarica commented on docs/javascript/copy_maven_command.js
> +    } else {
Small thing, this "else" seems like it's not needed, we can remove one nesting

2022-04-19 14:46 UTC, LetoBukarica approved these changes

2022-04-19 14:49 UTC, merged