New adaper structure in archetype
IKOR-GmbH/sip-framework pull request #106
Opened 2022-04-14 07:07 UTC by Nemikor

# Description

Adding redesigned adapter structure to archetype

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Creating a new adapter and testing all SIP functionalities

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing (regression) unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-27 06:53 UTC, MartinBuchheimIkor submitted a review, later dismissed

2022-05-24 13:38 UTC, vladiIkor commented on docs/README.md
> +logic is divided into three packages: **System A - Connector**, **System B - Connector** and **Common - Domain**.
Changes should go to docs-snapshot folder, righs?

2022-05-30 08:27 UTC, vladiIkor requested changes, later dismissed

2022-05-30 08:27 UTC, vladiIkor commented on changelogs/feature/new_adapter_structure.json
> +  "message": "Replace archetype structure with new simplified one."
This is very important change, we should be as precise as possible, hints:

- It's a new adapter structure, not archetype. 
- Switching from multi module adapters to no modules application structure

2022-05-30 08:27 UTC, vladiIkor commented on docs/README.md
>  **Domain**
Domain or Common?

2022-05-30 08:27 UTC, vladiIkor commented on docs/README.md
> +Also, it separates the system connectors from each other to allow loose coupling between them. Domain package should not contain any
'Also, it separates the system connectors from each other to allow loose coupling between them.' - not true anymore, it does not separate anything and does not give loose coupling.

The remaining text is true, but I'm afraid it becomes hard to understand in current format. The sub title is Common, and we start talking about common package than all of a sudden the story switches to domain package.

2022-05-30 08:27 UTC, vladiIkor commented on docs/README.md
> +│   │       └───domain
connector2?

2022-05-30 08:27 UTC, vladiIkor commented on docs/README.md
>  The image below shows the modules structure of a single SIP adapter.
The image needs to be updated as well. Currently it shows dependencies between modules etc.

2022-05-30 11:27 UTC, vladiIkor commented on sip-archetype/src/main/resources/archetype-resources/pom.xml
> +        <dependency>
If we want this dependency on the each adapter (which seams like a reasonable choice), we should add the dependency to sip-integration-starter.

2022-05-31 13:43 UTC, LetoBukarica approved these changes

2022-05-31 13:48 UTC, merged