Default error handler and bridging consumers to error handler
IKOR-GmbH/sip-framework pull request #189
Opened 2023-02-13 10:50 UTC by Nemikor

# Description

Please include a summary of the change and which issue (add a link) is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [ ] Test A
- [ ] Test B

**Test Configuration**:
* SIP Framework version(s):
* Other configuration:

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing (regression) unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-13 11:33 UTC, LetoBukarica requested changes

2023-02-13 11:33 UTC, LetoBukarica commented on sip-core/src/main/java/de/ikor/sip/foundation/core/declarative/errorhandler/SIPDefaultErrorHandler.java
> +package de.ikor.sip.foundation.core.declarative.errorhandler;
Can this go to core.configuration? It seems bigger than declarative piece.

2023-02-13 11:33 UTC, LetoBukarica commented on sip-core/src/main/java/de/ikor/sip/foundation/core/declarative/utils/DeclarativeHelper.java
> +  public static EndpointConsumerBuilder resolveEndpointProperties(
Can this be something like activateBridgeErrorHandler? resolveEndpointProperties confused me on the inboundEndpoint place.

2023-02-13 11:33 UTC, LetoBukarica commented on sip-core/src/main/java/de/ikor/sip/foundation/core/declarative/connector/GenericInboundConnectorBase.java
> +        .from(endpointConsumerBuilder)
Are we covered on the Rest Connector also? There is some difference in implementation there.

2023-02-14 13:24 UTC, LetoBukarica approved these changes

2023-02-14 14:02 UTC, nikolag-ikor approved these changes

2023-02-14 15:05 UTC, merged