Updated Camel version to 3.13.0. Fixed conflicting unit tests.
IKOR-GmbH/sip-framework pull request #24
Opened 2021-12-01 09:59 UTC by Nemikor

# Description

Update Apache Camel version to 3.13.0

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

On an existing or new adapter test all existing SIP Framework features and run all unit tests.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing (regression) unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-01 10:17 UTC, vladiIkor requested changes
Thumb up for fixing test names!

2021-12-01 10:17 UTC, vladiIkor commented on sip-core/src/test/java/de/ikor/sip/foundation/core/actuator/health/ftp/FtpHealthConsumersTest.java
>  import static org.junit.jupiter.api.Assertions.*;
Could we replace jupiter with assertj here?

2021-12-02 08:26 UTC, vladiIkor approved these changes

2021-12-02 08:29 UTC, nikolag-ikor approved these changes

2021-12-02 09:17 UTC, Dzuci approved these changes

2021-12-08 09:29 UTC, merged