Loops in process and scenario orchestration
IKOR-GmbH/sip-framework pull request #254
Opened 2024-04-22 09:22 UTC by Nemikor

# Description

Add doWhile and for loop in process and scenario orchestration DSL.

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing (regression) unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-24 08:52 UTC, MartinBuchheim requested changes

2024-04-24 08:52 UTC, MartinBuchheim commented on sip-core/src/main/java/de/ikor/sip/foundation/core/declarative/orchestration/scenario/dsl/ForScenarioProvidersBaseDefinition.java
> +   * iterations</code> matches at runtime for an integration call of the underlying scenario.
revert to previous wording

2024-04-24 08:52 UTC, MartinBuchheim commented on sip-core/src/main/java/de/ikor/sip/foundation/core/declarative/orchestration/scenario/dsl/ForScenarioProvidersBaseDefinition.java
> +  public WhileLoopCallScenarioConsumerDefinition<S, M>.Branch<
javadoc

2024-04-24 08:52 UTC, MartinBuchheim commented on sip-core/src/main/java/de/ikor/sip/foundation/core/declarative/orchestration/scenario/dsl/ForScenarioProvidersBaseDefinition.java
> +  public ForLoopCallScenarioConsumerDefinition<S, M>.Branch<
javadoc

2024-04-24 09:05 UTC, MartinBuchheim commented
Please also rename endLoop() to endDoWhile() for while-loops

2024-04-24 10:43 UTC, Nemikor commented on sip-core/src/main/java/de/ikor/sip/foundation/core/declarative/orchestration/scenario/dsl/ForScenarioProvidersBaseDefinition.java
> +   * iterations</code> matches at runtime for an integration call of the underlying scenario.
reverted

2024-05-03 13:55 UTC, MartinBuchheim approved these changes, later dismissed

2024-05-03 13:56 UTC, malte-westendorf-ikor submitted a review, later dismissed

2024-05-03 14:57 UTC, MartinBuchheim approved these changes

2024-05-03 14:59 UTC, merged