Add parameter descriptions to swagger
IKOR-GmbH/sip-framework pull request #3
Opened 2021-11-15 12:43 UTC by Nemikor

Added @Parameter description to operation variables in AdapterRouteEndpoint displaying permitted actions.

2021-11-15 16:34 UTC, smirglagit approved these changes, later dismissed

2021-11-15 16:40 UTC, nikolag-ikor approved these changes, later dismissed

2021-11-22 09:52 UTC, vladiIkor approved these changes

2021-11-22 10:34 UTC, vladiIkor requested changes

2021-11-22 10:34 UTC, vladiIkor commented on sip-core/src/main/java/de/ikor/sip/foundation/core/actuator/routes/AdapterRouteEndpoint.java
> +      @Parameter(
Given that "operation" parameter is reused twice (for now), we could encapsulate this @Parameter in new annotation with default values and reuse it.

2021-11-25 15:10 UTC, vladiIkor approved these changes

2021-12-01 10:14 UTC, merged