Packaging markdown files into jar. Structure for markdown files within adapter is changed.
IKOR-GmbH/sip-framework pull request #57
Opened 2022-02-07 08:02 UTC by nikolag-ikor

# Description

Added markdown files in jar. When running the adapter with jar, markdown files from adapter application module should be included and shown under /actuator/info endpoint.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Testing steps:
1. Create new adapter from archetype.
2. do mvn clean install in your adapter
3. Run the adapter and check if everything is there under /actuator/info
4. Run the jar of adapter and check actuator/info

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing (regression) unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-17 13:40 UTC, LetoBukarica requested changes
Looks good, small tweaks needed.

2022-02-17 13:40 UTC, LetoBukarica commented on sip-archetype/src/main/resources/archetype-resources/README.md
> +https://git.ikor.cloud/sip-2-product/sip/sip-framework/-/blob/develop/CONTRIBUTING.md
I think this should go to:
https://github.com/IKOR-GmbH/sip-framework/blob/develop/docs/CONTRIBUTING.md.

There is an another reference in the file that should go to README.md, not included in this changelog.

2022-02-17 13:40 UTC, LetoBukarica commented on sip-core/src/test/java/de/ikor/sip/foundation/core/actuator/routes/MarkdownFilesContributorTest.java
>  class MarkdownFilesContributorTest {
Can we have a little bit more tests to see how this works. What if there are 2 documents in the /documents folder, any error conditions?

2022-02-17 13:40 UTC, LetoBukarica commented on sip-core/src/test/resources/documents/README.md
> +https://git.ikor.cloud/sip-2-product/sip/sip-framework/-/blob/develop/README.md
Same as in previous file, references are to GitLab

2022-02-17 14:41 UTC, nikolag-ikor commented on sip-archetype/src/main/resources/archetype-resources/README.md
> +https://git.ikor.cloud/sip-2-product/sip/sip-framework/-/blob/develop/CONTRIBUTING.md
You are totally right. I will change these links, thanks!

2022-02-17 14:42 UTC, nikolag-ikor commented on sip-core/src/test/java/de/ikor/sip/foundation/core/actuator/routes/MarkdownFilesContributorTest.java
>  class MarkdownFilesContributorTest {
As a result of our call, I will try to implement it without using static files and will try to do it by creating files dynamically.

2022-02-17 15:15 UTC, Dzuci submitted a review, later dismissed
Tested with OK behavior.

2022-02-18 14:55 UTC, nikolag-ikor commented on sip-core/src/test/java/de/ikor/sip/foundation/core/actuator/routes/MarkdownFilesContributorTest.java
>  class MarkdownFilesContributorTest {
Refactored as desired. Reviewed by pair programming with @LetoBukarica.

2022-02-18 15:06 UTC, LetoBukarica approved these changes

2022-02-18 15:07 UTC, Dzuci approved these changes
Tested with OK behavior.

2022-02-18 15:25 UTC, merged