Documentation refactoring - small updates
IKOR-GmbH/sip-framework pull request #94
Opened 2022-03-23 07:30 UTC by nikolag-ikor

# Description

Documentation update after testing by creating adapter going step by step through the documentation.

- [x] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing (regression) unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-03-25 11:54 UTC, Nemikor submitted a review, later dismissed

2022-03-28 09:31 UTC, vladiIkor commented
In order to add new file to public git docs structure, you need to update mkdocs.yml:
https://github.com/IKOR-GmbH/sip-framework/pull/86/files

2022-03-28 09:33 UTC, vladiIkor requested changes
https://github.com/IKOR-GmbH/sip-framework/pull/94#issuecomment-1080414003

2022-04-06 13:46 UTC, vladiIkor approved these changes

2022-04-06 14:58 UTC, merged